[template]
src = "buckets.conf.tmpl"
dest = "/etc/nginx/sites-enabled/buckets"
keys = [
    "/s3proxy/bucket/name",
    "/s3proxy/aws/access/key",
    "/s3proxy/aws/secret/key",
]
check_cmd = "nginx -t 2>&1"
